/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ExpertSettings: typeof import('./components/ExpertSettings.vue')['default']
    GameGrid: typeof import('./components/GameGrid.vue')['default']
    MainMenu: typeof import('./components/MainMenu.vue')['default']
    MatchModal: typeof import('./components/MatchModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
